// NovaChair - Product Data & Types
// Design: Scandinavian Minimalism + Industrial Edge

export interface Product {
  id: string;
  name: string;
  category: string;
  categorySlug: string;
  price: number | null;
  wholesalePrice: number | null;
  wholesaleMinQty: number;
  description: string;
  shortDesc: string;
  image: string;
  images: string[];
  detailImage?: string;
  badge?: 'new' | 'best' | 'sale' | 'wholesale';
  discount?: number;
  stock: number;
  specs: Record<string, string>;
  tags: string[];
<<<<<<< Updated upstream
  retailAvailable?: boolean;
=======
  purchaseUrl: string;
>>>>>>> Stashed changes
}

export const CATEGORIES = [
  { slug: 'all', name: '전체', icon: '◈' },
  { slug: 'office-chair', name: '오피스 체어', icon: '◉' },
  { slug: 'gaming-chair', name: '게이밍 체어', icon: '◈' },
  { slug: 'sofa', name: '소파', icon: '◎' },
  { slug: 'table', name: '테이블', icon: '▣' },
  { slug: 'storage', name: '수납/선반', icon: '▤' },
];

// GitHub Public 폴더 기본 URL
const GITHUB_IMAGE_BASE = 'https://raw.githubusercontent.com/happyone118/novachair-images/main/';

export const PRODUCTS: Product[] = [
  {
    id: 'nc-001',
<<<<<<< Updated upstream
    name: 'STELLA',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: 89000,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 직접 제작한 플라스틱 인테리어 의자. 적재 가능한 스태킹 구조로 식당, 카페, 행사장 등 다양한 공간에 최적화되어 있습니다. 가볍고 내구성이 뛰어나며 관리가 편리합니다.',
    shortDesc: '공간을 채우는 프리미엄 감성',
    image: '/stella-main2.png',
    images: ['/stella-main2.png'],
    detailImage: '/STELLA-detail.jpg',
    badge: 'best',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
      '하중': '최대 150kg',
      '적재': '스태킹 가능',
      '색상': '화이트 / 베이지',
      '보증': '1년',
    },
    tags: ['플라스틱', '스태킹', '식당용', '카페용', '업소용'],
    retailAvailable: true,
  },
  {
    id: 'nc-101',
    name: '노바체어 두꺼비 1호',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '두꺼비 시리즈 1호',
    image: '/두꺼비1호.png',
    images: ['/두꺼비1호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '두꺼비', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-102',
    name: '노바체어 두꺼비 2호',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '두꺼비 시리즈 2호',
    image: '/두꺼비2호.png',
    images: ['/두꺼비2호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '두꺼비', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-103',
    name: '노바체어 두꺼비 3호',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '두꺼비 시리즈 3호',
    image: '/두꺼비3호.png',
    images: ['/두꺼비3호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '두꺼비', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-104',
    name: '노바체어 두꺼비 4호',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '두꺼비 시리즈 4호',
    image: '/두꺼비4호.png',
    images: ['/두꺼비4호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '두꺼비', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-105',
    name: '노바체어 두꺼비 5호 (팔걸이 있음)',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자. 팔걸이 포함.',
    shortDesc: '팔걸이 있는 두꺼비 5호',
    image: '/두꺼비5호_팔걸이.png',
    images: ['/두꺼비5호_팔걸이.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
      '팔걸이': '있음',
    },
    tags: ['플라스틱', '두꺼비', '팔걸이', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-106',
    name: '노바체어 두꺼비 5호 (팔걸이 없음)',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자. 팔걸이 없음.',
    shortDesc: '팔걸이 없는 두꺼비 5호',
    image: '/두꺼비5호_노팔걸이.png',
    images: ['/두꺼비5호_노팔걸이.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
      '팔걸이': '없음',
    },
    tags: ['플라스틱', '두꺼비', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-107',
    name: '노바체어 두꺼비 5-1호 (다리 고정)',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자. 다리 고정형.',
    shortDesc: '다리 고정형 두꺼비 5-1호',
    image: '/두꺼비5-1호.png',
    images: ['/두꺼비5-1호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
      '다리': '고정형',
    },
    tags: ['플라스틱', '두꺼비', '고정다리', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-108',
    name: '노바체어 매틱 6호',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '매틱 시리즈 6호',
    image: '/매틱6호.png',
    images: ['/매틱6호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '매틱', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-109',
    name: '노바체어 튤립 1호',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '튤립 시리즈 1호',
    image: '/튤립1호.png',
    images: ['/튤립1호.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '튤립', '인테리어'],
    retailAvailable: true,
  },
  {
    id: 'nc-110',
    name: '노바체어 깡통의자',
    category: '인테리어 의자',
    categorySlug: 'office-chair',
    price: null,
    wholesalePrice: null,
    wholesaleMinQty: 10,
    description: '국내 직영공장에서 제작한 플라스틱 인테리어 의자.',
    shortDesc: '깡통의자 시리즈',
    image: '/깡통의자.png',
    images: ['/깡통의자.png'],
    badge: 'new',
    stock: 500,
    specs: {
      '소재': 'PP (폴리프로필렌)',
      '제조': '국내 직영공장',
    },
    tags: ['플라스틱', '깡통', '인테리어'],
    retailAvailable: true,
=======
    name: '깡통의자',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 189000,
    wholesalePrice: 145000,
    wholesaleMinQty: 5,
    description: '심플하고 세련된 디자인의 깡통의자. 다양한 색상과 공간에 어울나는 미니멀 디자인입니다.',
    shortDesc: '심플한 깡통의자',
    image: `${GITHUB_IMAGE_BASE}ggangtong_black.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}ggangtong_black.jpg`,
      `${GITHUB_IMAGE_BASE}ggangtong_blue.jpg`,
    ],
    badge: 'best',
    stock: 45,
    specs: {
      '소재': '메탈 프레임',
      '색상': '블랙, 블루 외 다양',
      '하중': '최대 100kg',
      '높이': '약 80cm',
      '팔걸이': '없음',
      '보증': '1년',
    },
    tags: ['심플', '미니멀', '메탈'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13527892221',
  },
  {
    id: 'nc-002',
    name: '두꺼비 1호',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 249000,
    wholesalePrice: 189000,
    wholesaleMinQty: 5,
    description: '인체공학적 설계의 두꺼비 1호 의자. 편안한 앉음감과 세련된 디자인이 특징입니다.',
    shortDesc: '두꺼비 1호 의자',
    image: `${GITHUB_IMAGE_BASE}gubi_1-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_1-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_1-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_1-3.jpg`,
    ],
    badge: 'best',
    stock: 38,
    specs: {
      '소재': '패브릭',
      '프레임': '메탈',
      '하중': '최대 120kg',
      '높이 조절': '가능',
      '팔걸이': '있음',
      '보증': '2년',
    },
    tags: ['인체공학', '패브릭', '높이조절'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13402036513',
  },
  {
    id: 'nc-003',
    name: '두꺼비 2호',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 279000,
    wholesalePrice: 210000,
    wholesaleMinQty: 5,
    description: '편안한 앉음감의 두꺼비 2호 의자. 다양한 색상 옵션이 있습니다.',
    shortDesc: '두꺼비 2호 의자',
    image: `${GITHUB_IMAGE_BASE}gubi_2-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_2-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_2-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_2-3.jpg`,
    ],
    stock: 32,
    specs: {
      '소재': '패브릭',
      '프레임': '메탈',
      '하중': '최대 120kg',
      '높이 조절': '가능',
      '팔걸이': '있음',
      '보증': '2년',
    },
    tags: ['패브릭', '높이조절', '다색상'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13462124490',
  },
  {
    id: 'nc-004',
    name: '두꺼비 3호',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 299000,
    wholesalePrice: 225000,
    wholesaleMinQty: 5,
    description: '프리미엄 패브릭의 두꺼비 3호 의자. 고급스러운 디자인과 편안함을 제공합니다.',
    shortDesc: '두꺼비 3호 의자',
    image: `${GITHUB_IMAGE_BASE}gubi_3-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_3-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_3-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_3-3.jpg`,
    ],
    stock: 28,
    specs: {
      '소재': '프리미엄 패브릭',
      '프레임': '메탈',
      '하중': '최대 120kg',
      '높이 조절': '가능',
      '팔걸이': '있음',
      '보증': '2년',
    },
    tags: ['프리미엄', '패브릭', '고급'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13467843870',
  },
  {
    id: 'nc-005',
    name: '두꺼비 4호',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 329000,
    wholesalePrice: 249000,
    wholesaleMinQty: 5,
    description: '고급스러운 디자인의 두꺼비 4호 의자. 최상의 편안함을 제공합니다.',
    shortDesc: '두꺼비 4호 의자',
    image: `${GITHUB_IMAGE_BASE}gubi_4-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_4-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_4-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_4-3.jpg`,
    ],
    stock: 25,
    specs: {
      '소재': '프리미엄 패브릭',
      '프레임': '메탈',
      '하중': '최대 130kg',
      '높이 조절': '가능',
      '팔걸이': '있음',
      '보증': '2년',
    },
    tags: ['프리미엄', '고급', '편안함'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13468157649',
  },
  {
    id: 'nc-006',
    name: '두꺼비 5호 (팔걸이 있음)',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 379000,
    wholesalePrice: 289000,
    wholesaleMinQty: 5,
    description: '팔걸이가 있는 프리미엄 두꺼비 5호. 최고급 편안함을 제공합니다.',
    shortDesc: '두꺼비 5호 (팔걸이 있음)',
    image: `${GITHUB_IMAGE_BASE}gubi_5-1-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_5-1-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_5-1-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_5-1-3.jpg`,
    ],
    stock: 20,
    specs: {
      '소재': '프리미엄 패브릭',
      '프레임': '메탈',
      '하중': '최대 130kg',
      '높이 조절': '가능',
      '팔걸이': '있음',
      '보증': '2년',
    },
    tags: ['프리미엄', '팔걸이', '최고급'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13485782036',
  },
  {
    id: 'nc-007',
    name: '두꺼비 5호 (팔걸이 없음)',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 349000,
    wholesalePrice: 265000,
    wholesaleMinQty: 5,
    description: '팔걸이가 없는 두꺼비 5호. 깔끔한 디자인의 프리미엄 의자입니다.',
    shortDesc: '두꺼비 5호 (팔걸이 없음)',
    image: `${GITHUB_IMAGE_BASE}gubi_5-1-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_5-1-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_5-1-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_5-1-3.jpg`,
    ],
    stock: 22,
    specs: {
      '소재': '프리미엄 패브릭',
      '프레임': '메탈',
      '하중': '최대 130kg',
      '높이 조절': '가능',
      '팔걸이': '없음',
      '보증': '2년',
    },
    tags: ['프리미엄', '깔끔', '미니멀'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13486534951',
  },
  {
    id: 'nc-008',
    name: '두꺼비 5-1호 (다리고정)',
    category: '오피스 체어',
    categorySlug: 'office-chair',
    price: 359000,
    wholesalePrice: 272000,
    wholesaleMinQty: 5,
    description: '다리가 고정된 두꺼비 5-1호. 안정적인 사용감이 특징입니다.',
    shortDesc: '두꺼비 5-1호 (다리고정)',
    image: `${GITHUB_IMAGE_BASE}gubi_5-1-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}gubi_5-1-1.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_5-1-2.jpg`,
      `${GITHUB_IMAGE_BASE}gubi_5-1-3.jpg`,
    ],
    stock: 18,
    specs: {
      '소재': '프리미엄 패브릭',
      '프레임': '메탈',
      '하중': '최대 130kg',
      '높이 조절': '가능',
      '다리': '고정형',
      '보증': '2년',
    },
    tags: ['프리미엄', '안정적', '고정형'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13493520256',
  },
  {
    id: 'nc-009',
    name: '매틱 6호',
    category: '게이밍 체어',
    categorySlug: 'gaming-chair',
    price: 449000,
    wholesalePrice: 340000,
    wholesaleMinQty: 3,
    description: '게이밍과 업무용 겸용 매틱 6호. 다양한 색상으로 공간을 연출할 수 있습니다.',
    shortDesc: '매틱 6호 의자',
    image: `${GITHUB_IMAGE_BASE}matic_6-1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}matic_6-1.jpg`,
      `${GITHUB_IMAGE_BASE}matic_6-2.jpg`,
      `${GITHUB_IMAGE_BASE}matic_6-3.jpg`,
    ],
    badge: 'best',
    stock: 30,
    specs: {
      '소재': '메시 + 패브릭',
      '프레임': '메탈',
      '하중': '최대 150kg',
      '높이 조절': '가능',
      '팔걸이': '있음',
      '보증': '2년',
    },
    tags: ['게이밍', '업무용', '다색상'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13458545925',
  },
  {
    id: 'nc-010',
    name: '튤립',
    category: '소파',
    categorySlug: 'sofa',
    price: 599000,
    wholesalePrice: 455000,
    wholesaleMinQty: 2,
    description: '우아한 디자인의 튤립 소파. 거실을 한층 업그레이드시켜줍니다.',
    shortDesc: '튤립 소파',
    image: `${GITHUB_IMAGE_BASE}tulip_1.jpg`,
    images: [
      `${GITHUB_IMAGE_BASE}tulip_1.jpg`,
      `${GITHUB_IMAGE_BASE}tulip_2.jpg`,
      `${GITHUB_IMAGE_BASE}tulip_3.jpg`,
    ],
    badge: 'best',
    stock: 15,
    specs: {
      '크기': 'W180 × D85 × H75cm',
      '소재': '패브릭',
      '색상': '다양',
      '수용인원': '2~3인',
      '다리': '메탈',
      '보증': '2년',
    },
    tags: ['소파', '우아한', '거실'],
    purchaseUrl: 'https://smartstore.naver.com/happyone118/products/13413355327',
>>>>>>> Stashed changes
  },
];

export const SHOP_PRODUCTS = PRODUCTS.filter(p => p.retailAvailable);

export function formatPrice(price: number | null): string {
  if (!price) return '가격 문의';
  return price.toLocaleString('ko-KR') + '원';
}

export function getDiscountedPrice(price: number, discount?: number): number {
  if (!discount) return price;
  return Math.round(price * (1 - discount / 100));
}

export function getProductsByCategory(categorySlug: string): Product[] {
  if (categorySlug === 'all') return PRODUCTS;
  return PRODUCTS.filter((p) => p.categorySlug === categorySlug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getBestProducts(): Product[] {
  return PRODUCTS.filter((p) => p.badge === 'best');
}
